name: CI
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: "Deploy to server"
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    # needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Check if PM2 is installed
        run: |
          if which pm2 >/dev/null; then
            echo "PM2 is already installed"
          else
            npm install -g pm2
          fi
      - name: Check if dependencies are installed
        run: |
          if [ -d "node_modules" ]; then
            echo "Node modules already installed"
          else
            npm install
          fi
      - name: Build
        run: npm run build
      - name: Start Application with PM2
        working-directory: ./cicd-firstRepo
        run: |
          pm2 delete all
          pm2 start npm --name "app" -- start