name: CI
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to server"
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    # needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Check if PM2 is installed
        run: |
          if which pm2 >/dev/null; then
            echo "PM2 is already installed"
          else
            npm install -g pm2
          fi
      - name: npm install for project
        run: npm install
      - name: Start Application with PM2
        run: |
          pm2 start server.js