name: CI
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: "Deploy to server"
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.STAGING_SSH_KEY }}" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        # run: ssh -i ~/.ssh/private.key -o "StrictHostKeyChecking no" ubuntu@ec2-3-110-28-98.ap-south-1.compute.amazonaws.com -p ${{ secrets.STAGING_PORT }} whoami
        env:
          # SSH_USER: '${{ secrets.STAGING_SSH_USER }}'
          SSH_USER: 'ubuntu'
          SSH_KEY: '${{ secrets.STAGING_SSH_KEY }}'
          SSH_HOST: 'ec2-3-110-28-98.ap-south-1.compute.amazonaws.com'
          # SSH_HOST: '172-31-9-166'
      - uses: actions/checkout@v2
      - name: Check if PM2 is installed
        run: |
          if which pm2 >/dev/null; then
            echo "PM2 is already installed"
          else
            npm install -g pm2
          fi
      - name: npm install for project
        run: npm install
      # - name: Start Application with PM2
      #   run: |
      #     pm2 start server.js
      - name: Start the server
        if: ${{ always() }}
        run: ssh staging 'pm2 start server.js'

      - name: git checkout to develop
        run:  ssh staging 'git checkout develop'
      
      - name: pull remote develop to server
        run:  ssh staging 'git pull origin develop'