name: CI
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: "Deploy to server"
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    # needs: test
    steps:
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y ssh
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.STAGING_SSH_KEY }}" > ~/.ssh/ec2.pem
          chmod 600 ~/.ssh/ec2.pem
          ssh-keyscan ec2-3-110-28-98.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts
          cat >>~/.ssh/config <<END
          ssh -i ${{ secrets.STAGING_SSH_KEY }} -o "StrictHostKeyChecking no" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
        env:
          SSH_USER: 'ubuntu'
          SSH_KEY: '${{ secrets.STAGING_SSH_KEY }}'
          SSH_HOST: 'ec2-3-110-28-98.ap-south-1.compute.amazonaws.com'
      - uses: actions/checkout@v2
      # - name: Check permission of pem
      #   run: ls -l /home/runner/.ssh/ec2.pem
      # - name: open pem file
      #   run: cat /home/runner/.ssh/ec2.pem
      # - name: Check SSH connection1
      #   run: ssh -T staging
      # - name: Check SSH connection
      #   run: ssh staging hostname
      - name: Check if PM2 is installed
        run: |
          if which pm2 >/dev/null; then
            echo "PM2 is already installed"
          else
            npm install -g pm2
          fi
      - name: npm install for project
        run: npm install
      # - name: Start Application with PM2
      #   run: |
      #     pm2 start server.js
      - name: Start the server
        if: ${{ always() }}
        run: pm2 start server.js
        # run: ssh staging 'pm2 start server.js'

      - name: git checkout to develop
        run:  git checkout develop
        # run:  ssh staging 'git checkout develop'
      
      - name: pull remote develop to server
        run: |
            cd ll
        # git pull
        # run:  git pull origin develop
        # run:  ssh staging 'git pull origin develop'